#include <fstream>
#include <string>
#include <map>
#include <filesystem>
#include <iostream>
#include <chrono>
#include <thread>

#include "../headers/config.h"

using std::string;
using std::cout;
using std::filesystem::absolute;
using std::this_thread::sleep_for;

auto delay3MS = std::chrono::milliseconds(300);
auto delay2MS = std::chrono::milliseconds(200);

void showLoad() {

    cout << "</>Loading</>  ";
    for (int i = 0; i < 6; i++) {
        cout << "</>" << std::flush;
        sleep_for(delay3MS);
    }
    cout << "\n";
    sleep_for(500ms);
}

void showLoad2(const string& configFileName) {

    cout << "</>Searching For Configuration File</>  ";
    for (int i = 0; i < 6; i++) {
        cout << "</>" << std::flush;
        sleep_for(delay2MS);
    }
    cout << "  </>Completed</>";
    cout << "\n";
    sleep_for(800ms);

    if (std::filesystem::exists("configFileName")) {
        cout << "\n</>Found" << configFileName <<" in </>" << absolute(configFileName) << "</> \n";
        sleep_for(1000ms);
    }
}

void genDefault() {
    const string configFile = "corkus.config";
    
    std::ofstream file(configFile);
    if (!file.is_open()) {
        std::cerr << "</>Error: Unable to create configuration file!</>\n";
        return;
    }

    showLoad();



file << R"(#     ██████╗ ██████╗ ██████╗ ██╗  ██╗██╗   ██╗███████╗
#    ██╔════╝██╔═══██╗██╔══██╗██║ ██╔╝██║   ██║██╔════╝
#    ██║     ██║   ██║██████╔╝█████╔╝ ██║   ██║███████╗
#    ██║     ██║   ██║██╔══██╗██╔═██╗ ██║   ██║╚════██║
#    ╚██████╗╚██████╔╝██║  ██║██║  ██╗╚██████╔╝███████║
#     ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝ v1.2.1)";
    file << "\n\n#         An RS Project On GitHub ©2026 GPL 3.0\n\n";

    file << "\n# *** MAIN CONFIGURATION FILE ***\n";
    file << "# Generated by Corkus automatically\n";
    file << "# Generate and edit the user.config\n";
    file << "# for more information visit the GitHub page\n";
    
    file << "# *** Default Values ***\n";
    file << "Name=MyCoolMod\n";
    file << "DisplayName=Cool Mod Name\n";
    file << "DefaultDescription=My Cool Mod Project\n";
    file << "Author=YourNameHere\n";
    file << "Version=1.0.0\n";
    file << "Website=https://your-website.com\n\n";
    
    file << "# *** Default Output settings *** (leave default for 7dtd)\n";
    file << "XMLFileName=ModInfo.xml\n\n";
    
    file << "# *** Default Application Behavior ***\n";
    file << "WelcomeMessage=true\n";
    file << "PauseAfterCompletion=false\n";
    file << "AutoGenerateConfig=true\n";

    file.close();
    cout << "\nGenerated FILENAME >>> corkus.config <<<\n";
    cout << ">> PATH >> " << absolute ("corkus.config") << std::endl;
    std::this_thread::sleep_for(800ms);
}
void genCustom() {
    const string configFile = "user.config";

    std::ofstream file(configFile);
    if (!file.is_open()) {
        std::cerr << "</>Error: Unable to create configuration file!</>\n";
        return;
    }

    showLoad();



    file << R"(#     ██████╗ ██████╗ ██████╗ ██╗  ██╗██╗   ██╗███████╗
#    ██╔════╝██╔═══██╗██╔══██╗██║ ██╔╝██║   ██║██╔════╝
#    ██║     ██║   ██║██████╔╝█████╔╝ ██║   ██║███████╗
#    ██║     ██║   ██║██╔══██╗██╔═██╗ ██║   ██║╚════██║
#    ╚██████╗╚██████╔╝██║  ██║██║  ██╗╚██████╔╝███████║
#     ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝ v1.2.1)";

    file << "\n\n#         An RS Project On GitHub ©2026 GPL 3.0\n\n";

    file << "\n\n# *** USER CONFIGURATION FILE ***\n";
    file << "# Generated by Corkus\n";
    file << "# auto-generates a corkus.config for runtime anytime there is no file found\n";
    file << "# A Quick Guide For Users Below\n";
    file << "# - true or false only\n";
    file << "# - What you put here will be used as input\n";
    file << "# if you want to simply click 'Corkus' & generate\n";
    file << "# a file in the same directory\n";
    file << "# - The wiki will have more info soon\n";
    file << "# - Lines starting with # are commented out\n\n";

    file << "# *** Mod Values ***\n";
    file << "Name=MyCoolMod\n";
    file << "DisplayName=Cool Mod Name\n";
    file << "DefaultDescription=My Cool Mod Project\n";
    file << "Author=YourNameHere\n";
    file << "Version=1.0.0\n";
    file << "Website=https://your-website.com\n\n";

    file << "# *** Output settings *** (leave default for 7dtd)\n";
    file << "XMLFileName=ModInfo.xml\n\n";

    file << "# *** Application Behavior ***\n";
    file << "WelcomeMessage=true\n";
    file << "PauseAfterCompletion=false\n";
    file << "AutoGenerateConfig=true (For corkus.config only)\n ";

    file.close();
    cout << "\nGenerated FILENAME >>> user.config <<<\n";
    cout << ">> PATH >> " << absolute ("user.config") << std::endl;
    std::this_thread::sleep_for(800ms);
}


Config loadConfig() {

    showLoad2("configFileName");

    Config config;
    string configFile;

    if (std::filesystem::exists("user.config")) {
        configFile = "user.config";
        cout << "\n</>found user.config file @" << absolute("user.config") << "</>\n";
        cout << "\n</>Loading user.config file</>\n";
        showLoad();
    }
    else if (std::filesystem::exists("corkus.config")) {
        configFile = "corkus.config";
        cerr << "\n</>No user.config file found</>\n";
        cout << "\n</>Using corkus.config file @" << absolute("corkus.config") << "</>\n";
        showLoad();
    }
    else {

        cerr << "\n</>A Corkus Configuration file of any type was not found</>\n";
        cout << "\n</>Generating default file @" << absolute("corkus.config") << "</>\n";

        genDefault();

        return config;

    }

    std::ifstream file(configFile);
    if (!file.is_open()) {
        cout << "\n</>Configuration file not found.</>\n";
        cout << "\n</>Generating default file...</>\n";
        genDefault();
        return config;
    }

    string line;
    while (getline(file, line)) {

        if (line.empty() || line[0] == '#') continue;

        size_t pos = line.find('=');
        if (pos == string::npos) continue;

        string key = line.substr(0, pos);
        string value = line.substr(pos + 1);

        while (!key.empty() && (key.back() == ' ' || key.back() == '\t')) key.pop_back();
        while (!value.empty() && (value.front() == ' ' || value.front() == '\t')) value.erase(0, 1);

        if (key == "Author") config.dAuthor = value;
        else if (key == "Version") config.dVersion = value;
        else if (key == "Website") config.dWebsite = value;
        else if (key == "Name") config.dName = value;
        else if (key == "DisplayName") config.dDisName= value;
        else if (key == "DefaultDescription") config.dDesc = value;
        else if (key == "XMLFileName") config.output_filename = value;
        else if (key == "WelcomeMessage") config.show_welcome_message = (value == "true");
        else if (key == "PauseAfterCompletion") config.pause_after_completion = (value == "true");
        else if (key == "AutoGenerateConfig") config.auto_generate_config = (value == "true");
    }

    file.close();

    return config;
}
